name: smooth_page_indicator
description: Customizable animated page indicator with a set of built-in effects.
version: 1.0.0+2
homepage: https://github.com/Milad-Akarie/smooth_page_indicator

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  preload_page_view: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic:
